name: Build and Deploy Markdown Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List files in the repo (Debugging)
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -la

      - name: Generate HTML
        run: python generate.py
        working-directory: ${{ github.workspace }}  # If this doesn't work, try using ${{ github.workspace }}/markdown_blog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages

